const STATES = Object.freeze({
    CLOSED: 'CLOSED',
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
    ACCOUNT_ACTIVATION_REQUIRED: 'ACCOUNT_ACTIVATION_REQUIRED',
    ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
    ACCOUNT_ACTIVATION_TOKEN_INVALID: 'ACCOUNT_ACTIVATION_TOKEN_INVALID',
    RESET_ACCOUNT_TOKEN_INVALID: 'RESET_ACCOUNT_TOKEN_INVALID'
});

export {
    STATES
};