const STATES = Object.freeze({
    CLOSED: 'CLOSED',
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
    ACCOUNT_ACTIVATION_REQUIRED: 'ACCOUNT_ACTIVATION_REQUIRED'
});

export {
    STATES
};